# Generated by Django 5.1 on 2024-09-01 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=50, null=True, unique=True, verbose_name='Username')),
                ('email', models.CharField(max_length=50, verbose_name='Email')),
                ('password', models.CharField(max_length=50, verbose_name='Password')),
                ('user_type', models.CharField(choices=[('student', 'Student'), ('tutor', 'Tutor')], max_length=10, verbose_name='User Type')),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50, verbose_name='Full Name')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10, verbose_name='Gender')),
                ('qualifications', models.CharField(max_length=100, verbose_name='Qualifications')),
                ('subjects_offered', models.CharField(max_length=100, verbose_name='Subjects Offered')),
                ('level', models.CharField(choices=[('high school', 'High School'), ('secondary', 'Secondary')], max_length=20, verbose_name='Level')),
                ('street', models.CharField(max_length=100, verbose_name='Street')),
                ('city', models.CharField(max_length=50, verbose_name='City')),
                ('state', models.CharField(max_length=50, verbose_name='State')),
                ('pincode', models.CharField(max_length=10, verbose_name='Pincode')),
                ('availability', models.CharField(choices=[('offline', 'Offline'), ('online', 'Online'), ('both', 'Both')], max_length=20, verbose_name='Availability')),
                ('location_type', models.CharField(choices=[('home tuition', 'Home Tuition'), ('tutor location', 'Tutor Location')], max_length=20, verbose_name='Location Type')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50, verbose_name='Full Name')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10, verbose_name='Gender')),
                ('phone', models.CharField(max_length=15, verbose_name='Phone')),
                ('level', models.CharField(choices=[('high school', 'High School'), ('secondary', 'Secondary')], max_length=20, verbose_name='Level')),
                ('subject', models.CharField(max_length=50, verbose_name='Subject')),
                ('street', models.CharField(max_length=100, verbose_name='Street')),
                ('city', models.CharField(max_length=50, verbose_name='City')),
                ('state', models.CharField(max_length=50, verbose_name='State')),
                ('pincode', models.CharField(max_length=10, verbose_name='Pincode')),
                ('location_type', models.CharField(choices=[('home tuition', 'Home Tuition'), ('tutor location', 'Tutor Location')], max_length=20, verbose_name='Location Type')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
