# Generated by Django 5.1 on 2024-09-01 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=50, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='uname',
            field=models.CharField(default='', max_length=50, unique=True, verbose_name='Username'),
            preserve_default=False,
        ),
    ]
