# Generated by Django 5.1 on 2024-09-22 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_user_email_alter_user_uname'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='phone',
            field=models.CharField(default='', max_length=15, verbose_name='Phone'),
            preserve_default=False,
        ),
    ]
