# Generated by Django 5.1 on 2024-09-22 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_tutor_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(max_length=10, unique=True, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='phone',
            field=models.CharField(max_length=10, unique=True, verbose_name='Phone'),
        ),
    ]
