# Generated by Django 5.1 on 2024-10-12 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_student_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pics/default_profile.jpg', null=True, upload_to='profile_pics/tutors/'),
        ),
    ]
