# Generated by Django 5.1 on 2024-10-12 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_enquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='student_x',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='tutor_x',
            field=models.BooleanField(default=False),
        ),
    ]
