# Generated by Django 5.1 on 2024-10-27 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_classroom'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Session Date')),
                ('start_time', models.TimeField(verbose_name='Start Time')),
                ('end_time', models.TimeField(verbose_name='End Time')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Session Link')),
                ('location', models.TextField(blank=True, null=True, verbose_name='Offline Location')),
                ('mode', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], max_length=10, verbose_name='Session Mode')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='myapp.classroom')),
            ],
        ),
    ]
