# Generated by Django 5.1 on 2024-10-27 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_schedulesession'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulesession',
            name='notification_sent',
            field=models.BooleanField(default=False, verbose_name='Notification Sent'),
        ),
    ]
